PixelOS-AOSP/official_devices

API/devices.json, API/team.json
Change-Id: Id55bdd9d4f088b6c6c19651e7400655f6d5dfc97
=> Add up RMX2020 amd 10or G

API/devices.json, API/devices/hotdog.json, API/devices/hotdogg.json, API/team.json
- hotdog <> OnePlus 7T Pro.
- hotdogg <> OnePlus 7T Pro 5G McLaren Edition.
Signed-off-by: Cyber Knight <cyberknight755@gmail.com>
=> official_devices: Add `hotdog` and `hotdogg` to official devices

API/changelogs/RMX2020.md, API/devices/RMX2020.json
Change-Id: I7270a653c712584018a63945c71094611f7bb3e6
=> API: May 02, 2022 RMX2020 release

API/changelogs/RMX2020.md, API/devices/RMX2020.json
=> API: May 11, 2022 RMX2020 release

API/devices/gauguin.json, API/team.json
- Change device name to "Xiaomi 750G Series" too.
=> team: Change Maintainer for gauguin

API/changelogs/RMX2020.md, API/devices/RMX2020.json
Change-Id: Idea7c87b9c2db3fb066d839d6dd47848b6395cbf
=> API/devices: 12-Jun-2022 RMX2020 release

API/devices.json, API/devices/crownlte.json, API/devices/star2lte.json, API/devices/starlte.json, API/team.json
- starlte  <> Samsung Galaxy S9
- star2lte <> Samsung Galaxy S9+
- crownlte <> Samsung Galaxy Note 9
Signed-off-by: Seraphine <Seraphine312@gmail.com>
=> devices : Add starlte,star2lte,crownlte to official devices (#73)

API/changelogs/juice.md, API/devices/juice.json, API/instructions/juice.md
Signed-off-by: RayapKun <rayapkun@gmail.com>
=> API/devices: 18-Jun-2022 juice release

API/changelogs/gauguin.md, API/devices/gauguin.json
Signed-off-by: kawaaii <kawaaii@nocturn9x.space>
=> API: 18-June-2022 gauguin Release

API/changelogs/juice.md, API/devices/juice.json, API/instructions/juice.md
Signed-off-by: RayapKun <rayapkun@gmail.com>
=> API/devices: 09-July-2022 Juice releases

API/changelogs/gauguin.md, API/devices/gauguin.json, API/instructions/gauguin.md
Signed-off-by: kawaaii <kawaaii@nocturn9x.space>
=> API/devices: gauguin 16-7-22 update

API/devices.json, API/devices/cepheus.json, API/instructions/cepheus.md, API/team.json, API/updater/cepheus.json
=> official_devices: Add cepheus

API/updater/beryllium.json, API/updater/whyred.json
- also add friend donate link as I dont hab any :)
=> FIXUP ota for whyred

API/changelogs/RMX2020.md, API/devices/RMX2020.json
Change-Id: Ib2dd2275f5a488d2d2643cbb935d985d52b22c2e
=> API: RMX2020: 29/07/2022

API/changelogs/juice.md, API/devices/juice.json, API/instructions/juice.md, API/team.json
Signed-off-by: Raya Mahardika (rktdnt.) <rktdnt@proton.me>
=> API: juice: 13/Aug/2022 update

API/devices/gauguin.json
Signed-off-by: kawaaii <kawaaii@nocturn9x.space>
Change-Id: I78e5dcd46327abc0b5fa26eb09969f1b529cae14
=> API/devices: gauguin: Update Telegram ID

API/devices.json, API/devices/X00TD.json, API/team.json
Change-Id: I606114230ef426c6b1b1fe39e00533af0e191d69
=> official_devices: Welcome X00TD to the warzone

API/instructions/alioth.md
Signed-off-by: NotZeetaa <rodrigo2005contente@gmail.com>
=> API: alioth: Update flashing instructions

API/team.json
- People still don't recognize me who I am  ¯\_(ツ)_/¯
Change-Id: Iecf41cde265243b4df476408f2887e365ad1a1ab
=> API/team: Update gauguin's maintainer infos

API/devices.json, API/devices/beyond0lte.json, API/devices/beyond1lte.json, API/devices/beyond2lte.json, API/devices/beyondx.json, API/devices/d1.json, API/devices/d2s.json, API/devices/d2x.json, API/instructions/beyond0lte.md, API/instructions/beyond1lte.md, API/instructions/beyond2lte.md, API/instructions/beyondx.md, API/instructions/d1.md, API/instructions/d2s.md, API/instructions/d2x.md, API/team.json
Signed-off-by: Jubscleisson <fcodl0706@gmail.com>
=> devices: Add Samsung Galaxy 10 Series to official devices

API/team.json
Signed-off-by: NotZeetaa <rodrigo2005contente@gmail.com>
=> API: team: Add alioth maintainer

API/devices/citrus.json, API/devices/lime.json, API/instructions/citrus.md, API/instructions/lime.md, API/team.json
* follow PE changes https://github.com/PixelExperience/official_devices/commit/a7a0326a6ab8beb7f1b5bc3aaffdd9cd96122db3
=> devices: Deunified juice (lime/citrus)

API/devices.json, API/devices/X00T.json, API/team.json
Change-Id: I044e8b6bd34c1ed651d6ba1f185f4ff9e5d07373
=> official_devices: Drop X00T

API/devices/surya.json, API/team.json
This reverts commit 08031580425325f642a88742b783782f695990d0.
=> Revert "official_devices: Drop surya"

API/changelogs/spaced.md
=> API/devices: 03-May-2023 initial spaced release

API/devices.json, API/team.json
Change-Id: I43b64627f68823fa79e45ce858b7ada49176476e
=> API: Drop gauguin

API/devices.json, API/devices/munch.json
=> Revert "official_devices: Sleep well munch (#209)"

API/devices/gauguin.json
- Missed in commit [1].
[1]: e8666d6ea259c48f0f864db8e882a140e11e1c01 {"API: Drop gauguin"}
Change-Id: Iebb64c2aed610033fe3c7cd6fbcab3c80119ffee
=> API: devices: Drop gauguin

API/devices.json, API/devices/gauguin.json, API/team.json
- For my users: https://tinyurl.com/yhj2pv9s
Squashed commit of the following:
commit a7032394ef33718f1622d94e15bf8ce3bf0bed98
Author: hridaya <hridaya@pixelos.net>
Date:   Sun Jul 23 09:48:28 2023 +0545
Revert "API: Drop gauguin (#224)"
This reverts commit e8666d6ea259c48f0f864db8e882a140e11e1c01.
Change-Id: Id39298c172c44dbbfd001cf9426be9df3f1c2456
commit 593f84e9d835587978807cf02f015f2dd61bd80c
Author: hridaya <hridaya@pixelos.net>
Date:   Sun Jul 23 09:48:20 2023 +0545
Revert "fixup! API: devices: Drop gauguin (#227)"
This reverts commit 76687a257a9d2d2b81973aad4f57cb21028955bb.
Change-Id: Icae0f8c04f8d3db1a3e9d56e54a921b7ec8029c7
=> API: Revive gauguin

API/devices.json, API/devices/citrus.json, API/devices/lime.json, API/team.json
* cause i doesnt have that device anymore:(
=> API: Drop citrus and lime

API/devices.json, API/devices/porsche.json, API/team.json, API/updater/porsche.json
Change-Id: Ie2f39d13eefcaacd48b34fd0fbc6277298489114
=> porsche: Update maintainer

API/instructions/sunny.md
- We've updated to 14.0.3.0 sometime back.
=> API/instructions: Update fw requirements for sunny

API/devices/beryllium.json, API/devices/porsche.json, API/team.json
Change-Id: I3d464a4d8a0e9d147a09c8510ae6aa2ec36cb42a
=> devices: Update beryllium & porsche maintainer

API/devices/beryllium.json
Change-Id: Ia57599b2bc6a02c92450d70a2f585b0c57ad32ca
=> devices/beryllium: Promote to Fourteen

API/devices/beyond0lte.json, API/devices/beyond1lte.json, API/devices/beyond2lte.json, API/devices/beyondx.json, API/devices/d1.json, API/devices/d2s.json, API/devices/d2x.json, API/devices/f62.json
* Add xda link for f62/m62
* Set as beta
=> API: devices: exynos9820: Add fourteen to available versions

API/devices/munch.json
* Follow https://github.com/PixelOS-AOSP/official_devices/commit/fac45a6e939fddf9f426b5b8dd356188120b9cd1
=> API/devices: Mark munch stable

API/instructions/gauguin.md
Change-Id: I141b0aa43e8716fa177f07291e46719938a9b4a2
=> API/devices: Update instructions for gauguin

API/devices/marble.json, API/instructions/marble.md
=> API/devices: Update XDA thread link and instructions for marble

API/instructions/beryllium.md
- we have moved to retrofit dynamic partitions changing installation steps by a bit
Change-Id: I1f0808d6979fc6f48acd7ac936628fcf8870ad0e
=> API/Instructions: Redo Beryllium Instructions

API/devices.json, API/devices/hotdogg.json
- They've been EOL'd months ago but haven't been set as inactive here.
=> API: Sunset hotdog(g)

API/devices.json, API/devices/vayu.json, API/team.json
official_devices: Update vayu maintainer
=> official_devices: Update vayu maintainer

API/devices.json, API/devices/cancunf.json, API/team.json, API/updater/cancunf.json
Change-Id: Id4e6e70a1250cc59636463e2ec03c09dc565f8de
=> API/Devices: Welcome `cancunf` to PixelOS

API/devices/sky.json
=> official_devices: sky: Update device name

API/devices/beryllium.json, API/devices/vayu.json, API/team.json
Change-Id: I847f31f70b937d9cfcace088d3590ab27cdb2a56
=> official_devices: Update beryllium & vayu maintainer

API/devices/cupid.json
=> API/cupid.json: Add everyone's favourite forum link
